### ISSUE TITLE
Please update Expat from 2.2.0 to 2.2.8 with security fixes

### ISSUE THREAD

**Issue by hartwork** [rudix-mac/rudix#101]
https://github.com/libexpat/libexpat/releases/tag/R_2_2_8

Thank you!

**Comment by ruda** [comment]
4b3cad3878256e367efcecdf95bbb00bdbe2bbd2

**Comment by hartwork** [comment]
> [4b3cad3](https://github.com/rudix-mac/rudix/commit/4b3cad3878256e367efcecdf95bbb00bdbe2bbd2)

Was this meant to go to a different ticket?

**Comment by ruda** [comment]
Wrong hash pasted ;)
