### ISSUE TITLE
kind request for putting back packages

### ISSUE THREAD

**Issue by cg-cri-gl** [rudix-mac/rudix#123]
These days the compiled apps (rudix packages) have gone missing; any chance you put em back please ?
Thanks ! 

ps: for newcomers: The advantage of finding precompiled, self-sufficient (standalone) macos apps is evident : no need to install ruby, xcode .... and whatnot.

**Comment by ruda** [comment]
You are right, it was a mistake.

**Comment by ruda** [comment]
I will provide packages in a formal release here: https://github.com/rudix-mac/rudix/releases/tag/v2022

It's a work in progress, because I'm building packages on the top of GitHub services.

**Comment by cg-cri-gl** [comment]
Thanks!
as a side q: would you have perhaps have few infos to share on how this new (?) way of building packages would looks like / how to setup? 
sm asking because i own an older mac (mbp late 2011) with yosemite and, over time am now only able to find very few compatible programs including on your site rudix.org -and understanably so ( was looking for mc file manager and 7z-full / newer version)... and with 4 gb of ram don't know/Think this laptop is the right "builder machine" :) so no xcode here..
