### ISSUE TITLE
irssi formula broken on 10.6.8

### ISSUE THREAD

**Issue by amagumori** [rudix-mac/rudix#35]
over the past couple months i've made a couple attempts at trying to build and install irssi for OS X 10.6.8, with no success.  i saw rudix had a irssi package for 10.6.x so i thought i'd give it another shot.  it seemed to build and install just fine, but when i try to run irssi i get the following segmentation fault: 

```
[1]     30635 segmentation fault irssi
```

i tried running it with valgrind and got the following output:

==30840== Memcheck, a memory error detector
==30840== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==30840== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==30840== Command: irssi
==30840==
==30840== Invalid read of size 8
==30840==    at 0x10009526A: g_slice_alloc (in /usr/local/bin/irssi)
==30840==    by 0x100096265: g_slist_append (in /usr/local/bin/irssi)
==30840==    by 0x1000741EC: config_node_section_index (in /usr/local/bin/irssi)
==30840==    by 0x1000750E5: config_open (in /usr/local/bin/irssi)
==30840==    by 0x100075152: config_open (in /usr/local/bin/irssi)
==30840==    by 0x10007534D: config_parse (in /usr/local/bin/irssi)
==30840==    by 0x100070B85: irssi_config_is_changed (in /usr/local/bin/irssi)
==30840==    by 0x100071A3B: settings_init (in /usr/local/bin/irssi)
==30840==    by 0x1000607A1: core_init (in /usr/local/bin/irssi)
==30840==    by 0x100013844: main (in /usr/local/bin/irssi)
==30840==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==30840==
==30840==
==30840== Process terminating with default action of signal 10 (SIGBUS)
==30840==  Non-existent physical address at address 0x10
==30840==    at 0x10009526A: g_slice_alloc (in /usr/local/bin/irssi)
==30840==    by 0x100096265: g_slist_append (in /usr/local/bin/irssi)
==30840==    by 0x1000741EC: config_node_section_index (in /usr/local/bin/irssi)
==30840==    by 0x1000750E5: config_open (in /usr/local/bin/irssi)
==30840==    by 0x100075152: config_open (in /usr/local/bin/irssi)
==30840==    by 0x10007534D: config_parse (in /usr/local/bin/irssi)
==30840==    by 0x100070B85: irssi_config_is_changed (in /usr/local/bin/irssi)
==30840==    by 0x100071A3B: settings_init (in /usr/local/bin/irssi)
==30840==    by 0x1000607A1: core_init (in /usr/local/bin/irssi)
==30840==    by 0x100013844: main (in /usr/local/bin/irssi)
==30840==
==30840== HEAP SUMMARY:
==30840==     in use at exit: 483,990 bytes in 1,671 blocks
==30840==   total heap usage: 2,440 allocs, 769 frees, 600,366 bytes allocated
==30840==
==30840== LEAK SUMMARY:
==30840==    definitely lost: 0 bytes in 0 blocks
==30840==    indirectly lost: 0 bytes in 0 blocks
==30840==      possibly lost: 960 bytes in 4 blocks
==30840==    still reachable: 482,942 bytes in 1,666 blocks
==30840==         suppressed: 88 bytes in 1 blocks
==30840== Rerun with --leak-check=full to see details of leaked memory
==30840==
==30840== For counts of detected and suppressed errors, rerun with: -v
==30840== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
[1]    30840 bus error  valgrind irssi

i don't know any C, so i apologize if this is something trivial like it being built for the wrong architecture or something..

**Comment by KDGNOR** [comment]
did u ever fix it? 
I got same thing.
