### ISSUE TITLE
Missing git package?

### ISSUE THREAD

**Issue by epatters** [rudix-mac/rudix#54]
When I run `rudix upgrade`, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/rudix", line 748, in <module>
    sys.exit(main())
  File "/usr/local/bin/rudix", line 745, in main
    return options.command(options, args)
  File "/usr/local/bin/rudix", line 588, in command_update
    p_remote.version) >= 0:
AttributeError: 'list' object has no attribute 'version'
```
After some investigation, I discovered that the `git` package is missing from the repository

http://rudix.org/download/2014/10.10/

This results in `p_remote` being equal to `[]`.

Perhaps two fixes are in order?

1. Give a more informative error message when a remote package is missing or has been removed.
2. Upload a build of the git package.

**Comment by mrmstevenson** [comment]
I'm having similar problems finding git packages from this Master. 

According to the Readme Under Easy Install it says run this command. 

curl -O https://raw.github.com/rudix-mac/package-manager/master/rudix.py

Yet this file does not exist ???

**Comment by ruda** [comment]
The code should have a conditional to protect when p_remote is [] (empty). I will use None in this case and test for this situation. Fix coming soon.

The `git` package is now available but it still break for `python-ipython`, as reported.

**Comment by ruda** [comment]
So the idea of giving more information is interesting, here's how it will be displayed (it requires `--verbose`):

```
sudo ./rudix.py  update --verbose
Processing package git: Already in the latest version
Processing package lua: Already in the latest version
Processing package python-ipython: No updates available
All packages are up to date
```

**Comment by epatters** [comment]
Thanks for the fix!

**Comment by ruda** [comment]
:)

On Wed, Apr 29, 2015 at 5:35 PM, Evan Patterson <notifications@github.com>
wrote:

> Thanks for the fix!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudix-mac/rudix/issues/54#issuecomment-97576597>.
>



-- 
Rudá Moura
http://rudamoura.com/
