### ISSUE TITLE
Travis can't find rudix?

### ISSUE THREAD

**Issue by erip** [rudix-mac/rudix#59]
I'm contributing to a project that relies on rudix for CI, but travis errors because rudix couldn't be found when issuing:

`curl -O -L https://raw.github.com/rudix-mac/package-manager/master/rudix.py`

Strangely, when I issue it at the command-line, it works fine. Have you ever heard of this?

Thanks,
erip

**Comment by GeekHades** [comment]
The link have not the file, Could you gave me the right link

**Comment by ruda** [comment]
The URL had changed sometime due a structural change in GitHub, so the correct URL is `https://raw.githubusercontent.com/rudix-mac/rpm/master/rudix.py`.
