### ISSUE TITLE
10.11

### ISSUE THREAD

**Issue by AleksTJ** [rudix-mac/rudix#60]
Please OS X 10.11 (El Capitan) support.

**Comment by dclobato** [comment]
It's working fine on my El Capitan...

**Comment by react** [comment]
It looks like you can't install it from scratch on 10.11

    nibbler:Downloads $ sudo python rudix.py install rudix
    No match for 'rudix'

    nibbler:Downloads $ sudo python rudix.py -t
    Rudix 2015 on OS X 10.11 (?)
    0 packages(s) installed on volume '/'
    0 package(s) available on 'https://raw.githubusercontent.com/rudix-mac/packages/2015/10.11'

**Comment by ruda** [comment]
@react there's the new version of rudix.py with OS X 10.11 support and packages. `https://raw.githubusercontent.com/rudix-mac/rpm/2015.10.20/rudix.py` (it's now on the rudix.org). Please, test it. The packages were built from Yosemite but they should work equal on El Capitan.

**Comment by react** [comment]
Finally got around to trying it out and it works fine. Thanks!

**Comment by aml11** [comment]
This is happening again in high sierra :(
```
curl -O https://raw.githubusercontent.com/rudix-mac/rpm/2016.12.13/rudix.py
sudo python rudix.py install rudix

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25527  100 25527    0     0  82581      0 --:--:-- --:--:-- --:--:-- 82345
Password:
No match for 'rudix'
```

**Comment by mcandre** [comment]
@aml11 I get the same error.

Worse, when I install rudix via the Sierra .pkg, `sudo rudix install wget` and `sudo rudix search fail to find the wget package, even after running `sudo rudix update`.
