### ISSUE TITLE
can't synchronize?

### ISSUE THREAD

**Issue by gaming-hacker** [rudix-mac/rudix#63]
sudo rudix install grep
Could not synchronize with 'https://raw.githubusercontent.com/rudix-mac/package

opens to a blank page?

**Comment by ruda** [comment]
The correct URL is `https://raw.githubusercontent.com/rudix-mac/packages`.
What's the OS X version and the rudix version? It works for me.

**Comment by gaming-hacker** [comment]
ah, there's a typo 

osx 10.11
rudix  -v 
org.rudix.pkg.rudix version 2015.10.20-0 (install: Tue Nov  3 16:44:14 2015)
