### ISSUE TITLE
lftp 4.7.3

### ISSUE THREAD

**Issue by dzg** [rudix-mac/rudix#65]
How can I get lftp v4.7.3 on my Mac?

**Comment by dkmillares** [comment]
You can simply download the pkg for your OS X version and install it. Or you can install Rudix package manager, and then install lftp via "rudix -i lftp"

;)
http://rudix.org/packages/lftp.html

**Comment by dzg** [comment]
Thanks but that rudix link shows the latest version as 4.6.0

**Comment by dkmillares** [comment]
I didnt saw the version on packages.
In this case, I dont know how to help you, sorry =/

**Comment by abdelkafiahmed** [comment]
You can still build lftp from source !
